### ISSUE TITLE
escaping in queries

### ISSUE THREAD

**Issue by karpatov** [Patent2net/Patent2Net#7]
Hello,
Is it possible to escape "-" in request? "-" does not help,

I use your scripts under linux from command line (python OPSGatherPatentsv2.py). 
(I am not sure if ti was intended for such usage - I needed to move Requete + change R/r in the name, strip white space in secretkey...)

When a query contains "-" like in "anti-xxxxx" I get the following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/x/Downloads/Patent2Net-master/Current/OPSGatherPatentsv2.py", line 153, in <module>
    temp,  nbTrouves = PatentSearch(registered_client, requete, len(lstBrevets)+1, len(lstBrevets)+25)
  File "Ops3.py", line 375, in PatentSearch
    patents = data[u'ops:world-patent-data'][ u'ops:biblio-search'][u'ops:search-result'][u'ops:publication-reference']
KeyError: u'ops:publication-reference'runfile('/home/x/Downloads/Patent2Net-master/Current/OPSGatherPatentsv2.py', wdir=r'/home/x/Downloads/Patent2Net-master/Current')

also does the tool search in fulltext?
thank you

**Comment by cvanderlei** [comment]
Hi Karpatov,

I'm not sure if the script alone will be usefull, it's better if you dowload all the files and build the system or go to http://patent2net.vlab4u.info/ and dowload the executable version. At this url you can check the link "How to use the Patent2Net" to be sure you have done all requirements to make it work, for example, to get an EPO key to use in your own cles-epo.txt.

Regards,

**Comment by karpatov** [comment]
Hello, thanks for helping me.

so the software cannot be run as a set of py scripts under linux. (it looked working fine at leas grabbing abstracts, if I sticked to queries without problematic chars like "-") ...

I installed Win7 in order to use the version with interface.

1) Unfortunatly http://patent2net.vlab4u.info/P2N.zip is a dead  link.

2) do I need to compile?
if I download zip from the mainpage
https://github.com/Patent2net/Patent2Net 
I have Patent2Net-master dir containing Current and Development dirs + ApplicationPatent2net.exe
but it is not working.
ApplicationPatent2net.exe complines about unknown Collec

I tried compile.bat. 
it complains about missing tl85.dll and tc185.dll, please could you tell me where to get them (if they are open source)? Or is it problem of Win7 64bit ?
After the compilation I get a bunch of exes and if I move ApplicationPatent2net.exe/xml/pdb + CollectETraite.bat and run ApplicationPatent2net.exe something is happening but the comp freezes....

thanks for advice

**Comment by karpatov** [comment]
also webmaster@patent2net.vlab4u.info is not working.

**Comment by cvanderlei** [comment]
Hi,
Yes, it seems that the vlab4u is under maintenance. I can share with you the last version that I'm sure it works in Google Drive, send me a GMail mail. To compile you need to have Pythonxy with a combination of modules that I not sure all of them, I got it by try and fail. 

Regards,

**Comment by cvanderlei** [comment]
About the "-", did you try to use wildcards (?, *) in substitution of it.

**Comment by cvanderlei** [comment]
I think it is not necessary to have your email, try to access the Google Drive folder using this link:
https://drive.google.com/folderview?id=0B_qgjokHE3xoZ1ZveEszSW1IbTA&usp=sharing

There are 2 zip files, the last tested version (p2n_1) and the current version (p2n_2)
